---
title: "Untitled"
author: "Paul Theodor Pyl"
date: "14 Jun 2015"
output:
  ioslides_presentation:
    css: style.css
runtime: shiny
---

## Shiny Presentation

```{r, echo=FALSE}
inputPanel(
  sliderInput("s", label = "Sequencing Depth:",
              min = 10, max = 100, step = 10, value = 20),
  
  sliderInput("af", label = "Expected allele frequency:",
              min = 0.1, max = 1, value = 0.5, step = 0.1),
  
  checkboxInput("count", label = "Show Allele Frequency", value = TRUE)
)

renderPlot({
  plot(
    seq(0,input$s),
    dbinom(x = seq(0, input$s), size = input$s, prob = input$af),
    type = "h", xlab = "Allele Frequency (#SNV / #Reference)", ylab = "Binomial Model Density",
    main = paste( "Example with sequencing depth", input$s )
    )
})
```

## Wacko
```{r, echo=FALSE, message=FALSE, eval=TRUE,}
require(h5vc)
tallyFile <- system.file( "extdata", "example.tally.hfs5", package = "h5vcData" )
sampleData <- getSampleData( tallyFile, "/ExampleStudy/16" )
position <- 29983015

windowsize <- 1000
vars <- h5dapply( # Calling Variants
  filename = tallyFile,
  group = "/ExampleStudy/16",
  blocksize = 500,
  FUN = callVariantsPaired,
  sampledata = sampleData,
  cl = vcConfParams(returnDataPoints=TRUE),
  names = c("Coverages", "Counts", "Reference", "Deletions"),
  range = c(position - windowsize, position + windowsize)
)
vars <- do.call( rbind, vars ) # merge the results from all blocks by row

windowsize = 30

data <- h5readBlock(
  filename = tallyFile,
  group = "/ExampleStudy/16",
  names = c("Coverages", "Counts", "Deletions", "Reference"),
  range = c(position - windowsize, position + windowsize)
)

mismatchPlot(
  data = data,
  sampledata = sampleData,
  samples = subset(sampleData, Patient == "Patient5")$Sample,
  windowsize = windowsize,
  position = 1234
)
```
